{
  "name": "{{APP_TAG}}-app",
  "version": "1.0.0",
  "description": "PWA autogenerated",
  "main": "index.js",
  "dependencies": {
    "@webcomponents/webcomponentsjs": "^2.2.4",
    "lit-element": "^2.0.0",
    "pwa-helpers": "^0.9.0",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  },
  "keywords": [
    "lit-element",
    "redux",
    "catsys"
  ],
  "author": "Together we're more",
  "license": "MIT"
}
