{
  "name": "{{APP_TAG}}-app",
  "version": "1.0.0",
  "description": "PWA autogenerated",
  "main": "index.js",
  "dependencies": {
    "@webcomponents/webcomponentsjs": "^2.2.4",
    "lit-element": "^2.0.0",
    "@polymer/paper-button": "^3.0.1"
  },
  "keywords": [
    "lit-element",
    "catsys"
  ],
  "author": "Together we're more",
  "license": "MIT"
}
